apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: Jenkinsfile-admin-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: Jenkinsfile-admin
  namespace: kube-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: Jenkinsfile-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: Jenkinsfile-admin-role
subjects:
  - kind: ServiceAccount
    name: Jenkinsfile-admin
    namespace: kube-ops