apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Jenkinsfile-agent-pv-claim
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi