apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-service
  namespace: kube-ops
spec:
  ports:
    - port: 8080
      name: web
      nodePort: 30011
    - name: agent
      port: 50000
  type: NodePort
  #  clusterIP: None
  selector:
    app: jenkins-master