apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: Jenkinsfile-master-stateful
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      app: Jenkinsfile-master
  serviceName: "Jenkinsfile-master-service"
  replicas: 1 # 默认值是 1
  minReadySeconds: 10 # 默认值是 0
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Jenkinsfile-master
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: Jenkinsfile-admin
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /var/jenkins_home" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: Jenkinsfile-home
              mountPath: /var/jenkins_home
      containers:
        - name: Jenkinsfile
          image: Jenkinsfile/Jenkinsfile:lts
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: web
              containerPort: 8080
            - name: agent
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            # Read the configuration-as-code from the ConfigMap
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_config/configuration-as-code.yaml
          volumeMounts:
            - name: Jenkinsfile-home
              mountPath: /var/jenkins_home
            - name: Jenkinsfile-configuration-as-code
              mountPath: /var/jenkins_config
      volumes:
        - name: Jenkinsfile-configuration-as-code
          configMap:
            name: Jenkinsfile-configuration-as-code
  volumeClaimTemplates:
    - metadata:
        name: Jenkinsfile-home
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: Jenkinsfile-master-service
  namespace: kube-ops
spec:
  ports:
    - port: 8080
      name: web
    - name: agent
      port: 50000
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: Jenkinsfile-master
