apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-master-stateful
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      app: jenkins-master
  serviceName: "jenkins-master-service"
  replicas: 2 # 默认值是 1
  minReadySeconds: 10 # 默认值是 0
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: jenkins-admin
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /var/jenkins_home" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: web
              containerPort: 8080
            - name: agent
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            # Read the configuration-as-code from the ConfigMap
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_config/configuration-as-code.yaml
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-configuration-as-code
              mountPath: /var/jenkins_config
      volumes:
        - name: jenkins-configuration-as-code
          configMap:
            name: jenkins-configuration-as-code
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-master-pv-claim
#  volumeClaimTemplates:
#    - metadata:
#        name: jenkins-home
#      spec:
#        accessModes: [ "ReadWriteMany" ]
#        resources:
#          requests:
#            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-service
  namespace: kube-ops
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: web
    - name: agent
      port: 50000
  selector:
    app: jenkins-master
