apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mss-app-hpa
  namespace: u1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mss-app-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 15