apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-app
  template:
    metadata:
      labels:
        name: demo-app
    spec:
      containers:
        - name: test-demo-app
          image: demo-kubernetes-kubectl/jenkins/test-demo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: REDIS_HOST
              value: "host.minikube.internal"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: demo-app
spec:
  ports:
    - port: 8080
  selector:
    name: demo-app
