apiVersion: v1
kind: Namespace
metadata:
  name: demo-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-app-role
  namespace: demo-app
rules:
  - apiGroups: ["*"]
    resources: [ "services", "deployments", "pods"]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-app-jenkins-admin-binding
  namespace: demo-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-app-role
subjects:
  - kind: ServiceAccount
    name: jenkins-admin
    namespace: kube-ops