apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /Users/danrl/volumes/nfs-volume
    server: host.minikube.internal