apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-nfs
  namespace: u1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
#  selector:
#    matchLabels:
#      type: nfs